# Generated by Django 5.0.14 on 2026-04-13 14:47

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("imaging_requests", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForecastResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("start_date", models.DateTimeField(verbose_name="Начало периода")),
                ("end_date", models.DateTimeField(verbose_name="Конец периода")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "В очереди"),
                            ("running", "Выполняется"),
                            ("completed", "Завершено"),
                            ("failed", "Ошибка"),
                            ("cancelled", "Отменено"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=True, verbose_name="Актуальный прогноз"
                    ),
                ),
                (
                    "total_requests",
                    models.IntegerField(default=0, verbose_name="Всего заявок"),
                ),
                (
                    "processed_requests",
                    models.IntegerField(default=0, verbose_name="Обработано заявок"),
                ),
                (
                    "total_opportunities",
                    models.IntegerField(default=0, verbose_name="Всего окон съёмки"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Сообщение об ошибке"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Завершён"
                    ),
                ),
            ],
            options={
                "verbose_name": "Результат прогнозирования",
                "verbose_name_plural": "Результаты прогнозирования",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImagingOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="Начало съёмки")),
                ("end_time", models.DateTimeField(verbose_name="Конец съёмки")),
                (
                    "duration_seconds",
                    models.FloatField(verbose_name="Длительность, сек"),
                ),
                (
                    "swath_geometry",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True,
                        geography=True,
                        null=True,
                        srid=4326,
                        verbose_name="Геометрия полосы",
                    ),
                ),
                ("roll_angle", models.FloatField(verbose_name="Угол крена, °")),
                (
                    "sun_elevation",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Угол возвышения солнца, °"
                    ),
                ),
                (
                    "sun_azimuth",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Азимут солнца, °"
                    ),
                ),
                (
                    "score",
                    models.FloatField(default=0.0, verbose_name="Оценка возможности"),
                ),
                (
                    "is_selected",
                    models.BooleanField(
                        default=False, verbose_name="Выбрана для планирования"
                    ),
                ),
            ],
            options={
                "verbose_name": "Возможность съёмки",
                "verbose_name_plural": "Возможности съёмки",
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="WeatherForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("forecast_time", models.DateTimeField(verbose_name="Время прогноза")),
                (
                    "area",
                    django.contrib.gis.db.models.fields.PolygonField(
                        geography=True, srid=4326, verbose_name="Область"
                    ),
                ),
                (
                    "cloud_coverage_percent",
                    models.FloatField(verbose_name="Облачность, %"),
                ),
                (
                    "source",
                    models.CharField(
                        default="GRIB2", max_length=100, verbose_name="Источник"
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(default=dict, verbose_name="Сырые данные"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Загружен"),
                ),
            ],
            options={
                "verbose_name": "Прогноз погоды",
                "verbose_name_plural": "Прогнозы погоды",
                "ordering": ["-forecast_time"],
            },
        ),
        migrations.CreateModel(
            name="ForecastRequestMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coverage_percent",
                    models.FloatField(default=0.0, verbose_name="Процент покрытия"),
                ),
                (
                    "opportunity_count",
                    models.IntegerField(default=0, verbose_name="Количество окон"),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecast_mappings",
                        to="imaging_requests.imagingrequest",
                        verbose_name="Заявка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Связь прогноз-заявка",
                "verbose_name_plural": "Связи прогноз-заявки",
            },
        ),
    ]
