# Generated by Django 5.0.14 on 2026-04-13 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("imaging_requests", "0002_initial"),
        ("planning", "0001_initial"),
        ("satellites", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="forecastresult",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создан пользователем",
            ),
        ),
        migrations.AddField(
            model_name="forecastrequestmapping",
            name="forecast",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="request_mappings",
                to="planning.forecastresult",
                verbose_name="Прогноз",
            ),
        ),
        migrations.AddField(
            model_name="imagingopportunity",
            name="forecast",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opportunities",
                to="planning.forecastresult",
                verbose_name="Прогноз",
            ),
        ),
        migrations.AddField(
            model_name="imagingopportunity",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opportunities",
                to="imaging_requests.imagingrequest",
                verbose_name="Заявка",
            ),
        ),
        migrations.AddField(
            model_name="imagingopportunity",
            name="satellite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="imaging_opportunities",
                to="satellites.satellite",
                verbose_name="КА",
            ),
        ),
        migrations.AddIndex(
            model_name="weatherforecast",
            index=models.Index(fields=["area"], name="planning_we_area_25094a_idx"),
        ),
        migrations.AddIndex(
            model_name="weatherforecast",
            index=models.Index(
                fields=["forecast_time"], name="planning_we_forecas_3cffd0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="forecastrequestmapping",
            unique_together={("forecast", "request")},
        ),
        migrations.AddIndex(
            model_name="imagingopportunity",
            index=models.Index(
                fields=["satellite", "start_time"],
                name="planning_im_satelli_82b147_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="imagingopportunity",
            index=models.Index(
                fields=["request", "start_time"], name="planning_im_request_e845f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="imagingopportunity",
            index=models.Index(
                fields=["is_selected"], name="planning_im_is_sele_df41d6_idx"
            ),
        ),
    ]
