# Generated by Django 5.0.14 on 2026-04-13 14:47

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ground_stations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlightTaskGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Номер группы"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("start_time", models.DateTimeField(verbose_name="Начало периода")),
                ("end_time", models.DateTimeField(verbose_name="Конец периода")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новое"),
                            ("approval", "Согласование"),
                            ("sent", "Отправлено"),
                            ("approved", "Одобрено"),
                            ("rejected", "Отклонено"),
                            ("executing", "Выполняется"),
                            ("completed", "Выполнено"),
                            ("cancelled", "Отменено"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "kup_task_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID в КУП"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлена"),
                ),
                (
                    "sent_to_kup_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Отправлено в КУП"
                    ),
                ),
            ],
            options={
                "verbose_name": "Группа ПЗ",
                "verbose_name_plural": "Группы ПЗ",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FlightTaskHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("new", "Новое"),
                            ("approval", "Согласование"),
                            ("sent", "Отправлено"),
                            ("approved", "Одобрено"),
                            ("rejected", "Отклонено"),
                            ("executing", "Выполняется"),
                            ("completed", "Выполнено"),
                            ("cancelled", "Отменено"),
                        ],
                        max_length=20,
                        verbose_name="Из статуса",
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("new", "Новое"),
                            ("approval", "Согласование"),
                            ("sent", "Отправлено"),
                            ("approved", "Одобрено"),
                            ("rejected", "Отклонено"),
                            ("executing", "Выполняется"),
                            ("completed", "Выполнено"),
                            ("cancelled", "Отменено"),
                        ],
                        max_length=20,
                        verbose_name="В статус",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата изменения"
                    ),
                ),
            ],
            options={
                "verbose_name": "История ПЗ",
                "verbose_name_plural": "История ПЗ",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FlightTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_number",
                    models.CharField(max_length=50, verbose_name="Номер ПЗ"),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("imaging", "Съёмка"),
                            ("dump", "Сброс"),
                            ("maneuver", "Манёвр"),
                        ],
                        default="imaging",
                        max_length=20,
                        verbose_name="Тип задания",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="Начало")),
                ("end_time", models.DateTimeField(verbose_name="Конец")),
                (
                    "duration_seconds",
                    models.FloatField(verbose_name="Длительность, сек"),
                ),
                (
                    "roll_angle",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Угол крена, °"
                    ),
                ),
                (
                    "pitch_angle",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Угол тангажа, °"
                    ),
                ),
                (
                    "swath_geometry",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True,
                        geography=True,
                        null=True,
                        srid=4326,
                        verbose_name="Геометрия полосы",
                    ),
                ),
                (
                    "data_volume_gb",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Объём данных, ГБ"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новое"),
                            ("approval", "Согласование"),
                            ("sent", "Отправлено"),
                            ("approved", "Одобрено"),
                            ("rejected", "Отклонено"),
                            ("executing", "Выполняется"),
                            ("completed", "Выполнено"),
                            ("cancelled", "Отменено"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "kup_status",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Статус в КУП"
                    ),
                ),
                (
                    "execution_result",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Результат выполнения"
                    ),
                ),
                (
                    "execution_quality",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Не указано"),
                            ("success", "Успешно"),
                            ("partial", "Частично"),
                            ("failed", "Неудача"),
                            ("requires_reshoot", "Требуется пересъёмка"),
                            ("requires_redump", "Требуется пересброс"),
                        ],
                        default="",
                        max_length=50,
                        verbose_name="Качество выполнения",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "executed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Выполнено"
                    ),
                ),
                (
                    "ground_station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dump_tasks",
                        to="ground_stations.groundstation",
                        verbose_name="Наземная станция",
                    ),
                ),
            ],
            options={
                "verbose_name": "Полётное задание",
                "verbose_name_plural": "Полётные задания",
                "ordering": ["start_time"],
            },
        ),
    ]
