# Generated by Django 5.0.14 on 2026-04-13 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("flight_tasks", "0001_initial"),
        ("imaging_requests", "0001_initial"),
        ("satellites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flighttask",
            name="imaging_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flight_tasks",
                to="imaging_requests.imagingrequest",
                verbose_name="Заявка на съёмку",
            ),
        ),
        migrations.AddField(
            model_name="flighttask",
            name="memory_masks_released",
            field=models.ManyToManyField(
                blank=True,
                to="satellites.memorymask",
                verbose_name="Освобождаемые маски",
            ),
        ),
    ]
