# Generated by Django 5.0.14 on 2026-04-13 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("flight_tasks", "0002_initial"),
        ("planning", "0001_initial"),
        ("satellites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flighttask",
            name="opportunity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flight_task",
                to="planning.imagingopportunity",
                verbose_name="Возможность съёмки",
            ),
        ),
        migrations.AddField(
            model_name="flighttask",
            name="satellite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flight_tasks",
                to="satellites.satellite",
                verbose_name="КА",
            ),
        ),
    ]
