# Generated by Django 5.0.14 on 2026-04-13 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("flight_tasks", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="flighttaskgroup",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создан пользователем",
            ),
        ),
        migrations.AddField(
            model_name="flighttask",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flight_tasks",
                to="flight_tasks.flighttaskgroup",
                verbose_name="Группа",
            ),
        ),
        migrations.AddField(
            model_name="flighttaskhistory",
            name="changed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Изменено пользователем",
            ),
        ),
        migrations.AddField(
            model_name="flighttaskhistory",
            name="flight_task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="flight_tasks.flighttask",
                verbose_name="ПЗ",
            ),
        ),
        migrations.AddIndex(
            model_name="flighttask",
            index=models.Index(
                fields=["satellite", "start_time"],
                name="flight_task_satelli_956f89_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="flighttask",
            index=models.Index(fields=["status"], name="flight_task_status_3d8d2b_idx"),
        ),
        migrations.AddIndex(
            model_name="flighttask",
            index=models.Index(
                fields=["task_type"], name="flight_task_task_ty_b560ec_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="flighttask",
            unique_together={("group", "task_number")},
        ),
    ]
