# Generated by Django 5.0.14 on 2026-04-13 14:47

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GroundStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Код"),
                ),
                (
                    "station_type",
                    models.CharField(
                        choices=[
                            ("control", "ЗСУ (Земная станция управления)"),
                            ("data_reception", "ЗС ПД (Земная станция приёма данных)"),
                        ],
                        max_length=20,
                        verbose_name="Тип станции",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326, verbose_name="Координаты"
                    ),
                ),
                (
                    "elevation_m",
                    models.FloatField(
                        default=0.0, verbose_name="Высота над уровнем моря, м"
                    ),
                ),
                (
                    "min_elevation_angle",
                    models.FloatField(
                        default=5.0, verbose_name="Мин. угол возвышения, °"
                    ),
                ),
                (
                    "max_elevation_angle",
                    models.FloatField(
                        default=90.0, verbose_name="Макс. угол возвышения, °"
                    ),
                ),
                (
                    "data_rate_mbps",
                    models.FloatField(
                        default=100.0, verbose_name="Скорость передачи, Мбит/с"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активна"),
                            ("inactive", "Неактивна"),
                            ("maintenance", "Обслуживание"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлена"),
                ),
            ],
            options={
                "verbose_name": "Наземная станция",
                "verbose_name_plural": "Наземные станции",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["location"], name="ground_stat_locatio_953191_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ForbiddenZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название зоны"),
                ),
                (
                    "area",
                    django.contrib.gis.db.models.fields.PolygonField(
                        geography=True, srid=4326, verbose_name="Область запрета"
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Начало действия"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Конец действия"
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="Причина")),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forbidden_zones",
                        to="ground_stations.groundstation",
                        verbose_name="Станция",
                    ),
                ),
            ],
            options={
                "verbose_name": "Зона запрета",
                "verbose_name_plural": "Зоны запрета",
                "indexes": [
                    models.Index(fields=["area"], name="ground_stat_area_5e9dbd_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="CommunicationSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="Начало слота")),
                ("end_time", models.DateTimeField(verbose_name="Конец слота")),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Доступен"),
                ),
                (
                    "reserved_for",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Зарезервирован для"
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communication_slots",
                        to="ground_stations.groundstation",
                        verbose_name="Станция",
                    ),
                ),
            ],
            options={
                "verbose_name": "Слот связи",
                "verbose_name_plural": "Слоты связи",
                "ordering": ["start_time"],
                "indexes": [
                    models.Index(
                        fields=["station", "start_time", "end_time"],
                        name="ground_stat_station_606b18_idx",
                    ),
                    models.Index(
                        fields=["is_available"], name="ground_stat_is_avai_d75bf0_idx"
                    ),
                ],
            },
        ),
    ]
