# Generated by Django 5.0.14 on 2026-04-13 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Satellite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "norad_id",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="NORAD ID"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "swath_width_km",
                    models.FloatField(default=10.0, verbose_name="Полоса захвата, км"),
                ),
                (
                    "max_roll_angle",
                    models.FloatField(default=30.0, verbose_name="Макс. угол крена, °"),
                ),
                (
                    "max_pitch_angle",
                    models.FloatField(
                        default=30.0, verbose_name="Макс. угол тангажа, °"
                    ),
                ),
                (
                    "max_yaw_angle",
                    models.FloatField(
                        default=30.0, verbose_name="Макс. угол рыскания, °"
                    ),
                ),
                (
                    "max_memory_gb",
                    models.FloatField(default=100.0, verbose_name="Макс. память, ГБ"),
                ),
                (
                    "current_memory_usage_gb",
                    models.FloatField(
                        default=0.0, verbose_name="Текущая загрузка памяти, ГБ"
                    ),
                ),
                (
                    "power_consumption_per_image",
                    models.FloatField(
                        default=50.0, verbose_name="Расход энергии на снимок"
                    ),
                ),
                (
                    "available_power",
                    models.FloatField(default=500.0, verbose_name="Доступная энергия"),
                ),
                (
                    "min_altitude_km",
                    models.FloatField(default=400.0, verbose_name="Мин. высота, км"),
                ),
                (
                    "max_altitude_km",
                    models.FloatField(default=1200.0, verbose_name="Макс. высота, км"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активен"),
                            ("inactive", "Неактивен"),
                            ("maintenance", "Обслуживание"),
                            ("decommissioned", "Выведен из эксплуатации"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
            ],
            options={
                "verbose_name": "Космический аппарат",
                "verbose_name_plural": "Космические аппараты",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UnavailabilityPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="Начало")),
                ("end_time", models.DateTimeField(verbose_name="Конец")),
                ("reason", models.TextField(verbose_name="Причина")),
                (
                    "satellite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unavailability_periods",
                        to="satellites.satellite",
                        verbose_name="КА",
                    ),
                ),
            ],
            options={
                "verbose_name": "Период недоступности",
                "verbose_name_plural": "Периоды недоступности",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="MemoryMask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="Начало")),
                ("end_time", models.DateTimeField(verbose_name="Конец")),
                ("size_gb", models.FloatField(verbose_name="Размер, ГБ")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Описание"
                    ),
                ),
                (
                    "is_releasable",
                    models.BooleanField(default=True, verbose_name="Можно освободить"),
                ),
                (
                    "flight_task_id",
                    models.IntegerField(blank=True, null=True, verbose_name="ID ПЗ"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "satellite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memory_masks",
                        to="satellites.satellite",
                        verbose_name="КА",
                    ),
                ),
            ],
            options={
                "verbose_name": "Маска памяти",
                "verbose_name_plural": "Маски памяти",
                "ordering": ["-start_time"],
                "indexes": [
                    models.Index(
                        fields=["satellite", "start_time", "end_time"],
                        name="satellites__satelli_e8e19c_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TLEData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tle_line1",
                    models.CharField(max_length=69, verbose_name="TLE строка 1"),
                ),
                (
                    "tle_line2",
                    models.CharField(max_length=69, verbose_name="TLE строка 2"),
                ),
                ("epoch", models.DateTimeField(verbose_name="Эпоха")),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Загружено"),
                ),
                (
                    "is_current",
                    models.BooleanField(default=True, verbose_name="Актуальное"),
                ),
                (
                    "satellite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tle_history",
                        to="satellites.satellite",
                        verbose_name="КА",
                    ),
                ),
            ],
            options={
                "verbose_name": "TLE данные",
                "verbose_name_plural": "TLE данные",
                "ordering": ["-epoch"],
                "indexes": [
                    models.Index(
                        fields=["satellite", "-epoch"],
                        name="satellites__satelli_9727d1_idx",
                    ),
                    models.Index(
                        fields=["is_current"], name="satellites__is_curr_024ad8_idx"
                    ),
                ],
            },
        ),
    ]
