# Generated by Django 5.0.14 on 2026-04-13 14:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImagingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Номер заявки"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "target_area",
                    django.contrib.gis.db.models.fields.GeometryField(
                        geography=True, srid=4326, verbose_name="Целевая область"
                    ),
                ),
                (
                    "imaging_type",
                    models.CharField(
                        choices=[
                            ("standard", "Стандартная"),
                            ("night", "Ночная (угол солнца < 10°)"),
                            ("multi_polygon", "Мультиполигон"),
                            ("with_cutouts", "С вырезами"),
                        ],
                        default="standard",
                        max_length=20,
                        verbose_name="Тип съёмки",
                    ),
                ),
                (
                    "required_resolution",
                    models.FloatField(
                        default=1.0, verbose_name="Требуемое разрешение, м"
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=5,
                        help_text="1 - низкий, 10 - критический",
                        verbose_name="Приоритет (1-10)",
                    ),
                ),
                (
                    "earliest_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Раннее начало"
                    ),
                ),
                (
                    "latest_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Позднее окончание"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("approved", "Согласована"),
                            ("in_progress", "Выполняется"),
                            ("completed", "Завершена"),
                            ("cancelled", "Отменена"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Внешний ID"
                    ),
                ),
                (
                    "external_system",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Внешняя система"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлена"),
                ),
            ],
            options={
                "verbose_name": "Заявка на съёмку",
                "verbose_name_plural": "Заявки на съёмку",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImagingRequestAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="request_attachments/", verbose_name="Файл"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("shp", "Shapefile"),
                            ("geojson", "GeoJSON"),
                            ("kml", "KML"),
                            ("other", "Другое"),
                        ],
                        max_length=20,
                        verbose_name="Тип файла",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Загружен"),
                ),
            ],
            options={
                "verbose_name": "Вложение заявки",
                "verbose_name_plural": "Вложения заявок",
            },
        ),
        migrations.CreateModel(
            name="RequestHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("new", "Новая"),
                            ("approved", "Согласована"),
                            ("in_progress", "Выполняется"),
                            ("completed", "Завершена"),
                            ("cancelled", "Отменена"),
                        ],
                        max_length=20,
                        verbose_name="Из статуса",
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("approved", "Согласована"),
                            ("in_progress", "Выполняется"),
                            ("completed", "Завершена"),
                            ("cancelled", "Отменена"),
                        ],
                        max_length=20,
                        verbose_name="В статус",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата изменения"
                    ),
                ),
            ],
            options={
                "verbose_name": "История заявки",
                "verbose_name_plural": "История заявок",
                "ordering": ["-created_at"],
            },
        ),
    ]
