# Generated by Django 5.0.14 on 2026-04-13 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("imaging_requests", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="imagingrequest",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создана пользователем",
            ),
        ),
        migrations.AddField(
            model_name="imagingrequestattachment",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="imaging_requests.imagingrequest",
                verbose_name="Заявка",
            ),
        ),
        migrations.AddField(
            model_name="requesthistory",
            name="changed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Изменено пользователем",
            ),
        ),
        migrations.AddField(
            model_name="requesthistory",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="imaging_requests.imagingrequest",
                verbose_name="Заявка",
            ),
        ),
        migrations.AddIndex(
            model_name="imagingrequest",
            index=models.Index(
                fields=["target_area"], name="imaging_req_target__8108cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="imagingrequest",
            index=models.Index(fields=["status"], name="imaging_req_status_630fe5_idx"),
        ),
        migrations.AddIndex(
            model_name="imagingrequest",
            index=models.Index(
                fields=["priority"], name="imaging_req_priorit_0a5d65_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="imagingrequest",
            index=models.Index(
                fields=["earliest_start", "latest_end"],
                name="imaging_req_earlies_bd62d8_idx",
            ),
        ),
    ]
